# Site settings
title: "HANSANG LEE"
description: "Machine Learning Engineer in Medical Image Analysis"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "HANSANG LEE"
resume_title:                   "Post-Doc Researcher @ KAIST"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hansanglee@kaist.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am a post-doctoral researcher at Statistical Inference and Information Theory Laboratory (SIIT) in School of Electrical Engineering, Korea Advanced Institute of Science and Technology (KAIST). I am interested in developing machine learning methods for processing, analyzing, and understanding medical images for various applications. The tasks I've worked on include organ/tissue segmentation, tumor/lesion classification, abnormality detection, and survival prediction.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true
resume_section_publications:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/thehansanglee"
  resume_twitter_url:           "https://twitter.com/thehansanglee"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/thehansanglee"
  resume_linkedin_url:          "https://www.linkedin.com/in/thehansanglee/"
  resume_instagram_url:         "https://www.instagram.com/thehansanglee/"
  resume_website_url:           "https://scholar.google.co.kr/citations?hl=en&authuser=4&user=ufb3VdEAAAAJ"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
